feature/ECCW-655
essexcountycouncil/essex-gov-uk-drupal pull request #334
Opened 2023-11-06 09:29 UTC by kurtisRogers-Nomensa

- Added config for card display mode
- Added view block for event cards
- Added styles

2023-11-06 09:39 UTC, kurtisRogers-Nomensa commented
![image](https://github.com/essexcountycouncil/essex-gov-uk-drupal/assets/118725785/76c98668-20da-49e7-8f88-d262d183656b)

2023-11-06 09:46 UTC, Polynya requested changes
It's best to `git checkout` any config changes you know aren't related to the ticket. I can do revert the files before this is merged.

2023-11-06 09:46 UTC, Polynya commented on config/default/cludo_search.settings.yml
> -engineId: '10581'
Revert this change

2023-11-06 09:46 UTC, Polynya commented on config/default/system.site.yml
> -  front: /node/1211
Revert this change

2023-11-06 09:46 UTC, Polynya commented on config/default/webform.webform.feedback_form.yml
> -  info:
Revert this file

2023-11-07 13:46 UTC, MatthewWilkes commented
@kurtisRogers-Nomensa Can you also change the title of this PR to explain what it does and look at combining the description and your first comment into something more aligned with the PR template we discussed last month?

2024-01-31 12:47 UTC, closed without merging